definitions:
  business.Customer:
    properties:
      createdAt:
        type: string
      customerName:
        type: string
      customerPhone:
        type: string
      customerStatus:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      updatedAt:
        type: string
    type: object
  common.PageResult:
    properties:
      list: {}
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  common.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  customer.CreateCustomerRequest:
    properties:
      customerName:
        type: string
      customerPhone:
        type: string
      customerStatus:
        type: string
    required:
    - customerName
    - customerPhone
    type: object
  customer.DeleteCustomerRequest:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  customer.UpdateCustomerRequest:
    properties:
      customerName:
        type: string
      customerPhone:
        type: string
      customerStatus:
        type: string
      id:
        type: integer
    required:
    - id
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  login.LoginRequest:
    properties:
      code:
        type: string
      code_id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  login.SysCaptchaResponse:
    properties:
      captchaId:
        type: string
      captchaLength:
        type: integer
      openCaptcha:
        type: boolean
      picPath:
        type: string
    type: object
  system.ExaFileUploadAndDownload:
    properties:
      ID:
        description: 主键ID
        type: integer
      classId:
        description: 分类id
        type: integer
      createdAt:
        description: 创建时间
        type: string
      key:
        description: 编号
        type: string
      name:
        description: 文件名
        type: string
      tag:
        description: 文件标签
        type: string
      updatedAt:
        description: 更新时间
        type: string
      url:
        description: 文件地址
        type: string
    type: object
  system.SysUser:
    properties:
      authorityId:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      headerImg:
        type: string
      id:
        type: integer
      nickName:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  user.ChangePasswordRequest:
    properties:
      newPassword:
        description: 新密码
        type: string
      oldPassword:
        description: 旧密码
        type: string
    type: object
info:
  contact: {}
  description: 使用gin+vue进行极速开发的全栈开发基础平台
  title: Gin-Vue-Admin API
  version: v1.0
paths:
  /customer:
    delete:
      consumes:
      - application/json
      description: 删除客户
      parameters:
      - description: 客户ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/customer.DeleteCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除客户
      tags:
      - Customer
    post:
      consumes:
      - application/json
      description: 创建客户
      parameters:
      - description: 客户姓名, 客户电话
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/customer.CreateCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/business.Customer'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建客户
      tags:
      - Customer
    put:
      consumes:
      - application/json
      description: 更新客户
      parameters:
      - description: 客户ID, 客户姓名, 客户电话
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/customer.UpdateCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/business.Customer'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 更新客户
      tags:
      - Customer
  /customer/list:
    get:
      consumes:
      - application/json
      description: 分页获取客户列表
      parameters:
      - in: query
        name: keyword
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/common.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取客户列表
      tags:
      - Customer
  /login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/login.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  additionalProperties: true
                  type: object
                msg:
                  type: string
              type: object
      summary: 用户登录
      tags:
      - Login
  /login/captcha:
    get:
      description: 生成验证码
      produces:
      - application/json
      responses:
        "200":
          description: 生成验证码
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/login.SysCaptchaResponse'
                msg:
                  type: string
              type: object
      summary: 生成验证码
      tags:
      - Login
  /login/logout:
    post:
      consumes:
      - application/json
      description: 登出
      produces:
      - application/json
      responses:
        "200":
          description: 登出
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 登出
      tags:
      - Login
  /upload:
    delete:
      consumes:
      - application/json
      description: 删除文件
      parameters:
      - description: 文件Key
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/system.ExaFileUploadAndDownload'
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除文件
      tags:
      - File
    post:
      consumes:
      - multipart/form-data
      description: 上传文件
      parameters:
      - description: 文件
        in: formData
        name: file
        required: true
        type: file
      - description: 分类ID
        in: formData
        name: classId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 上传成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/system.ExaFileUploadAndDownload'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 上传文件
      tags:
      - File
  /upload/list:
    get:
      consumes:
      - application/json
      description: 分页获取文件列表
      parameters:
      - in: query
        name: keyword
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/common.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取文件列表
      tags:
      - File
  /user:
    post:
      consumes:
      - application/json
      description: 创建用户
      parameters:
      - description: 用户名, 昵称, 头像, 角色ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/system.SysUser'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建用户
      tags:
      - User
    put:
      consumes:
      - application/json
      description: 更新用户
      parameters:
      - description: 用户ID, 昵称, 头像, 角色ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/system.SysUser'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 更新用户
      tags:
      - User
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: 删除用户
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - User
  /user/changePassword:
    post:
      consumes:
      - application/json
      description: 修改用户密码
      parameters:
      - description: 旧密码, 新密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/user.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 修改成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 修改用户密码
      tags:
      - User
  /user/list:
    get:
      consumes:
      - application/json
      description: 分页获取用户列表
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/common.Response'
            - properties:
                data:
                  $ref: '#/definitions/common.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取用户列表
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
